### PR TITLE
[WIP] Update environment

### PR DESCRIPTION
**Pull request by duboism**
This PR updates the `environment.yml` and `requirements.txt` files to match the current production environment (`igwn-py39`).

This addresses some limitations in #7 and some of the issues in #9 (see the discussion in those issues).

We also do some minor modifications:
  - clarify instruction for Mac using Apple processors
  - enhance scripts used to check the versions

### CODE REVIEW

**Comment by agoodmanjerry** [comment]
Hi @duboism ,
Thank you very much for making the version of the packages synced with igwn-py39. I have tested the tutorials using the conda environment built from environment.yml. Everything went well except for one line in environment.yml.
The line 22 should be pycbc==2.4.0 to be the same as igwn-py39. Other than that, everything is fine and this PR should be merged.

**Comment by camurria** [comment]
Ok, I am confirming the merge and then I'll add what is missing

**Comment by duboism** [comment]
Arf, you were too fast... I wanted to make some modifications (including what we discussed on Friday) but haven't had time. Sorry about that.

**Comment by camurria** [comment]
Don't worry, I did what was missing in a separate commit :-)

**Pull request merged**
